//
//  AppPalettes.swift
//  AppModules
//
//  Created by Hao Tran on 25/9/25.
//

import SwiftUI

public enum AppPalettes {
    // ---------- LIGHT (standard) ----------
    public static let light = AppColors(
        brightness: .light,
        primary: Color(hex: 0xff904a44),
        surfaceTint: Color(hex: 0xff904a44),
        onPrimary: Color(hex: 0xffffffff),
        primaryContainer: Color(hex: 0xffffdad6),
        onPrimaryContainer: Color(hex: 0xff73332e),
        secondary: Color(hex: 0xff775653),
        onSecondary: Color(hex: 0xffffffff),
        secondaryContainer: Color(hex: 0xffffdad6),
        onSecondaryContainer: Color(hex: 0xff5d3f3c),
        tertiary: Color(hex: 0xff715b2e),
        onTertiary: Color(hex: 0xffffffff),
        tertiaryContainer: Color(hex: 0xfffedfa6),
        onTertiaryContainer: Color(hex: 0xff584419),
        error: Color(hex: 0xffba1a1a),
        onError: Color(hex: 0xffffffff),
        errorContainer: Color(hex: 0xffffdad6),
        onErrorContainer: Color(hex: 0xff93000a),
        surface: Color(hex: 0xfffff8f7),
        onSurface: Color(hex: 0xff231918),
        onSurfaceVariant: Color(hex: 0xff534341),
        outline: Color(hex: 0xff857371),
        outlineVariant: Color(hex: 0xffd8c2bf),
        shadow: Color(hex: 0xff000000),
        scrim: Color(hex: 0xff000000),
        inverseSurface: Color(hex: 0xff392e2d),
        inversePrimary: Color(hex: 0xffffb4ac),
        primaryFixed: Color(hex: 0xffffdad6),
        onPrimaryFixed: Color(hex: 0xff3b0907),
        primaryFixedDim: Color(hex: 0xffffb4ac),
        onPrimaryFixedVariant: Color(hex: 0xff73332e),
        secondaryFixed: Color(hex: 0xffffdad6),
        onSecondaryFixed: Color(hex: 0xff2c1513),
        secondaryFixedDim: Color(hex: 0xffe7bdb8),
        onSecondaryFixedVariant: Color(hex: 0xff5d3f3c),
        tertiaryFixed: Color(hex: 0xfffedfa6),
        onTertiaryFixed: Color(hex: 0xff261900),
        tertiaryFixedDim: Color(hex: 0xffe0c38c),
        onTertiaryFixedVariant: Color(hex: 0xff584419),
        surfaceDim: Color(hex: 0xffe8d6d4),
        surfaceBright: Color(hex: 0xfffff8f7),
        surfaceContainerLowest: Color(hex: 0xffffffff),
        surfaceContainerLow: Color(hex: 0xfffff0ef),
        surfaceContainer: Color(hex: 0xfffceae8),
        surfaceContainerHigh: Color(hex: 0xfff6e4e2),
        surfaceContainerHighest: Color(hex: 0xfff1dedc)
    )

    // ---------- LIGHT (medium contrast) ----------
    static let lightMedium = AppColors(
        brightness: .light,
        primary: Color(hex: 0xff5e231f),
        surfaceTint: Color(hex: 0xff904a44),
        onPrimary: Color(hex: 0xffffffff),
        primaryContainer: Color(hex: 0xffa15852),
        onPrimaryContainer: Color(hex: 0xffffffff),
        secondary: Color(hex: 0xff4b2f2c),
        onSecondary: Color(hex: 0xffffffff),
        secondaryContainer: Color(hex: 0xff876561),
        onSecondaryContainer: Color(hex: 0xffffffff),
        tertiary: Color(hex: 0xff463309),
        onTertiary: Color(hex: 0xffffffff),
        tertiaryContainer: Color(hex: 0xff816a3b),
        onTertiaryContainer: Color(hex: 0xffffffff),
        error: Color(hex: 0xff740006),
        onError: Color(hex: 0xffffffff),
        errorContainer: Color(hex: 0xffcf2c27),
        onErrorContainer: Color(hex: 0xffffffff),
        surface: Color(hex: 0xfffff8f7),
        onSurface: Color(hex: 0xff180f0e),
        onSurfaceVariant: Color(hex: 0xff413331),
        outline: Color(hex: 0xff5f4f4d),
        outlineVariant: Color(hex: 0xff7b6967),
        shadow: Color(hex: 0xff000000),
        scrim: Color(hex: 0xff000000),
        inverseSurface: Color(hex: 0xff392e2d),
        inversePrimary: Color(hex: 0xffffb4ac),
        primaryFixed: Color(hex: 0xffa15852),
        onPrimaryFixed: Color(hex: 0xffffffff),
        primaryFixedDim: Color(hex: 0xff84413b),
        onPrimaryFixedVariant: Color(hex: 0xffffffff),
        secondaryFixed: Color(hex: 0xff876561),
        onSecondaryFixed: Color(hex: 0xffffffff),
        secondaryFixedDim: Color(hex: 0xff6d4d4a),
        onSecondaryFixedVariant: Color(hex: 0xffffffff),
        tertiaryFixed: Color(hex: 0xff816a3b),
        onTertiaryFixed: Color(hex: 0xffffffff),
        tertiaryFixedDim: Color(hex: 0xff675225),
        onTertiaryFixedVariant: Color(hex: 0xffffffff),
        surfaceDim: Color(hex: 0xffd4c3c1),
        surfaceBright: Color(hex: 0xfffff8f7),
        surfaceContainerLowest: Color(hex: 0xffffffff),
        surfaceContainerLow: Color(hex: 0xfffff0ef),
        surfaceContainer: Color(hex: 0xfff6e4e2),
        surfaceContainerHigh: Color(hex: 0xffebd9d7),
        surfaceContainerHighest: Color(hex: 0xffdfcecc)
    )

    // ---------- LIGHT (high contrast) ----------
    static let lightHigh = AppColors(
        brightness: .light,
        primary: Color(hex: 0xff511a16),
        surfaceTint: Color(hex: 0xff904a44),
        onPrimary: Color(hex: 0xffffffff),
        primaryContainer: Color(hex: 0xff763630),
        onPrimaryContainer: Color(hex: 0xffffffff),
        secondary: Color(hex: 0xff3f2523),
        onSecondary: Color(hex: 0xffffffff),
        secondaryContainer: Color(hex: 0xff60423e),
        onSecondaryContainer: Color(hex: 0xffffffff),
        tertiary: Color(hex: 0xff3b2902),
        onTertiary: Color(hex: 0xffffffff),
        tertiaryContainer: Color(hex: 0xff5a461b),
        onTertiaryContainer: Color(hex: 0xffffffff),
        error: Color(hex: 0xff600004),
        onError: Color(hex: 0xffffffff),
        errorContainer: Color(hex: 0xff98000a),
        onErrorContainer: Color(hex: 0xffffffff),
        surface: Color(hex: 0xfffff8f7),
        onSurface: Color(hex: 0xff000000),
        onSurfaceVariant: Color(hex: 0xff000000),
        outline: Color(hex: 0xff362927),
        outlineVariant: Color(hex: 0xff554544),
        shadow: Color(hex: 0xff000000),
        scrim: Color(hex: 0xff000000),
        inverseSurface: Color(hex: 0xff392e2d),
        inversePrimary: Color(hex: 0xffffb4ac),
        primaryFixed: Color(hex: 0xff763630),
        onPrimaryFixed: Color(hex: 0xffffffff),
        primaryFixedDim: Color(hex: 0xff59201c),
        onPrimaryFixedVariant: Color(hex: 0xffffffff),
        secondaryFixed: Color(hex: 0xff60423e),
        onSecondaryFixed: Color(hex: 0xffffffff),
        secondaryFixedDim: Color(hex: 0xff472c29),
        onSecondaryFixedVariant: Color(hex: 0xffffffff),
        tertiaryFixed: Color(hex: 0xff5a461b),
        onTertiaryFixed: Color(hex: 0xffffffff),
        tertiaryFixedDim: Color(hex: 0xff423006),
        onTertiaryFixedVariant: Color(hex: 0xffffffff),
        surfaceDim: Color(hex: 0xffc6b5b3),
        surfaceBright: Color(hex: 0xfffff8f7),
        surfaceContainerLowest: Color(hex: 0xffffffff),
        surfaceContainerLow: Color(hex: 0xffffedea),
        surfaceContainer: Color(hex: 0xfff1dedc),
        surfaceContainerHigh: Color(hex: 0xffe2d0ce),
        surfaceContainerHighest: Color(hex: 0xffd4c3c1)
    )

    // ---------- DARK (standard) ----------
    static let dark = AppColors(
        brightness: .dark,
        primary: Color(hex: 0xffffb4ac),
        surfaceTint: Color(hex: 0xffffb4ac),
        onPrimary: Color(hex: 0xff561e1a),
        primaryContainer: Color(hex: 0xff73332e),
        onPrimaryContainer: Color(hex: 0xffffdad6),
        secondary: Color(hex: 0xffe7bdb8),
        onSecondary: Color(hex: 0xff442927),
        secondaryContainer: Color(hex: 0xff5d3f3c),
        onSecondaryContainer: Color(hex: 0xffffdad6),
        tertiary: Color(hex: 0xffe0c38c),
        onTertiary: Color(hex: 0xff3f2d04),
        tertiaryContainer: Color(hex: 0xff584419),
        onTertiaryContainer: Color(hex: 0xfffedfa6),
        error: Color(hex: 0xffffb4ab),
        onError: Color(hex: 0xff690005),
        errorContainer: Color(hex: 0xff93000a),
        onErrorContainer: Color(hex: 0xffffdad6),
        surface: Color(hex: 0xff1a1110),
        onSurface: Color(hex: 0xfff1dedc),
        onSurfaceVariant: Color(hex: 0xffd8c2bf),
        outline: Color(hex: 0xffa08c8a),
        outlineVariant: Color(hex: 0xff534341),
        shadow: Color(hex: 0xff000000),
        scrim: Color(hex: 0xff000000),
        inverseSurface: Color(hex: 0xfff1dedc),
        inversePrimary: Color(hex: 0xff904a44),
        primaryFixed: Color(hex: 0xffffdad6),
        onPrimaryFixed: Color(hex: 0xff3b0907),
        primaryFixedDim: Color(hex: 0xffffb4ac),
        onPrimaryFixedVariant: Color(hex: 0xff73332e),
        secondaryFixed: Color(hex: 0xffffdad6),
        onSecondaryFixed: Color(hex: 0xff2c1513),
        secondaryFixedDim: Color(hex: 0xffe7bdb8),
        onSecondaryFixedVariant: Color(hex: 0xff5d3f3c),
        tertiaryFixed: Color(hex: 0xfffedfa6),
        onTertiaryFixed: Color(hex: 0xff261900),
        tertiaryFixedDim: Color(hex: 0xffe0c38c),
        onTertiaryFixedVariant: Color(hex: 0xff584419),
        surfaceDim: Color(hex: 0xff1a1110),
        surfaceBright: Color(hex: 0xff423735),
        surfaceContainerLowest: Color(hex: 0xff140c0b),
        surfaceContainerLow: Color(hex: 0xff231918),
        surfaceContainer: Color(hex: 0xff271d1c),
        surfaceContainerHigh: Color(hex: 0xff322826),
        surfaceContainerHighest: Color(hex: 0xff3d3231)
    )

    // ---------- DARK (medium contrast) ----------
    static let darkMedium = AppColors(
        brightness: .dark,
        primary: Color(hex: 0xffffd2cd),
        surfaceTint: Color(hex: 0xffffb4ac),
        onPrimary: Color(hex: 0xff481310),
        primaryContainer: Color(hex: 0xffcc7b73),
        onPrimaryContainer: Color(hex: 0xff000000),
        secondary: Color(hex: 0xfffed2cd),
        onSecondary: Color(hex: 0xff381f1c),
        secondaryContainer: Color(hex: 0xffad8884),
        onSecondaryContainer: Color(hex: 0xff000000),
        tertiary: Color(hex: 0xfff7d8a0),
        onTertiary: Color(hex: 0xff332300),
        tertiaryContainer: Color(hex: 0xffa78d5b),
        onTertiaryContainer: Color(hex: 0xff000000),
        error: Color(hex: 0xffffd2cc),
        onError: Color(hex: 0xff540003),
        errorContainer: Color(hex: 0xffff5449),
        onErrorContainer: Color(hex: 0xff000000),
        surface: Color(hex: 0xff1a1110),
        onSurface: Color(hex: 0xffffffff),
        onSurfaceVariant: Color(hex: 0xffeed7d4),
        outline: Color(hex: 0xffc2adab),
        outlineVariant: Color(hex: 0xff9f8c8a),
        shadow: Color(hex: 0xff000000),
        scrim: Color(hex: 0xff000000),
        inverseSurface: Color(hex: 0xfff1dedc),
        inversePrimary: Color(hex: 0xff74352f),
        primaryFixed: Color(hex: 0xffffdad6),
        onPrimaryFixed: Color(hex: 0xff2c0102),
        primaryFixedDim: Color(hex: 0xffffb4ac),
        onPrimaryFixedVariant: Color(hex: 0xff5e231f),
        secondaryFixed: Color(hex: 0xffffdad6),
        onSecondaryFixed: Color(hex: 0xff200b09),
        secondaryFixedDim: Color(hex: 0xffe7bdb8),
        onSecondaryFixedVariant: Color(hex: 0xff4b2f2c),
        tertiaryFixed: Color(hex: 0xfffedfa6),
        onTertiaryFixed: Color(hex: 0xff190f00),
        tertiaryFixedDim: Color(hex: 0xffe0c38c),
        onTertiaryFixedVariant: Color(hex: 0xff463309),
        surfaceDim: Color(hex: 0xff1a1110),
        surfaceBright: Color(hex: 0xff4d4240),
        surfaceContainerLowest: Color(hex: 0xff0d0605),
        surfaceContainerLow: Color(hex: 0xff251b1a),
        surfaceContainer: Color(hex: 0xff302524),
        surfaceContainerHigh: Color(hex: 0xff3b302f),
        surfaceContainerHighest: Color(hex: 0xff463b3a)
    )

    // ---------- DARK (high contrast) ----------
    static let darkHigh = AppColors(
        brightness: .dark,
        primary: Color(hex: 0xffffece9),
        surfaceTint: Color(hex: 0xffffb4ac),
        onPrimary: Color(hex: 0xff000000),
        primaryContainer: Color(hex: 0xffffaea6),
        onPrimaryContainer: Color(hex: 0xff220001),
        secondary: Color(hex: 0xffffece9),
        onSecondary: Color(hex: 0xff000000),
        secondaryContainer: Color(hex: 0xffe3b9b4),
        onSecondaryContainer: Color(hex: 0xff190605),
        tertiary: Color(hex: 0xffffeed3),
        onTertiary: Color(hex: 0xff000000),
        tertiaryContainer: Color(hex: 0xffdcbf89),
        onTertiaryContainer: Color(hex: 0xff120a00),
        error: Color(hex: 0xffffece9),
        onError: Color(hex: 0xff000000),
        errorContainer: Color(hex: 0xffffaea4),
        onErrorContainer: Color(hex: 0xff220001),
        surface: Color(hex: 0xff1a1110),
        onSurface: Color(hex: 0xffffffff),
        onSurfaceVariant: Color(hex: 0xffffffff),
        outline: Color(hex: 0xffffece9),
        outlineVariant: Color(hex: 0xffd4bebb),
        shadow: Color(hex: 0xff000000),
        scrim: Color(hex: 0xff000000),
        inverseSurface: Color(hex: 0xfff1dedc),
        inversePrimary: Color(hex: 0xff74352f),
        primaryFixed: Color(hex: 0xffffdad6),
        onPrimaryFixed: Color(hex: 0xff000000),
        primaryFixedDim: Color(hex: 0xffffb4ac),
        onPrimaryFixedVariant: Color(hex: 0xff2c0102),
        secondaryFixed: Color(hex: 0xffffdad6),
        onSecondaryFixed: Color(hex: 0xff000000),
        secondaryFixedDim: Color(hex: 0xffe7bdb8),
        onSecondaryFixedVariant: Color(hex: 0xff200b09),
        tertiaryFixed: Color(hex: 0xfffedfa6),
        onTertiaryFixed: Color(hex: 0xff000000),
        tertiaryFixedDim: Color(hex: 0xffe0c38c),
        onTertiaryFixedVariant: Color(hex: 0xff190f00),
        surfaceDim: Color(hex: 0xff1a1110),
        surfaceBright: Color(hex: 0xff5a4d4c),
        surfaceContainerLowest: Color(hex: 0xff000000),
        surfaceContainerLow: Color(hex: 0xff271d1c),
        surfaceContainer: Color(hex: 0xff392e2d),
        surfaceContainerHigh: Color(hex: 0xff443938),
        surfaceContainerHighest: Color(hex: 0xff504443)
    )
}
